### ISSUE TITLE
How can I use current gem for Mongoid app?

### ISSUE THREAD

**Issue by bobur554396** [luizpicolo/rails_admin_dropzone#1]
I have app, where used rails_admin gem. How can i integrate dropzone to it?

**Comment by bobur554396** [comment]
Okay, thanks for response :)

вторник, 7 июня 2016 г. пользователь Luiz Picolo написал:

**Comment by luizpicolo** [comment]
Not at all :)

  
\--  

Atenciosamente

  

****

**_Luiz Picolo_** \- _Desenvolvedor Web_  
[www.linkedin.com/in/luizpicolo](http://www.linkedin.com/in/luizpicolo)  

[www.github.com/luizpicolo](http://www.github.com/luizpicolo)  

[www.luizpicolo.com.br](http://www.luizpicolo.com.br)

  
![](https://link.nylas.com/open/7tp57gvoq47n6ycssvb15cxwf/local-f6226a67-32eb)

On Jun 6 2016, at 5:32 pm, Bobur &lt;notifications@github.com&gt; wrote:  

> Okay, thanks for response :)  
  
вторник, 7 июня 2016 г. пользователь Luiz Picolo написал:  
  
&gt; Hi @bobur554396 &lt;https://github.com/bobur554396&gt;.  
&gt; I never used this gem with mongo. Really have to do some tests to verify  
&gt; if its operation.  
&gt; This can be a new future feature.  
&gt;  
&gt; —  
&gt; You are receiving this because you were mentioned.  
&gt; Reply to this email directly, view it on GitHub  
&gt; &lt;https://github.com/luizpicolo/rails_admin_dropzone/issues/1#issuecomm
ent-224093158&gt;,  
&gt; or mute the thread  
&gt; &lt;https://github.com/notifications/unsubscribe/AHtn_VV4txmGrkF6mDkyAq5-
rv4uitnzks5qJJAfgaJpZM4Iujbi&gt;  
&gt; .  
&gt;  

>

> —  
You are receiving this because you commented.  
Reply to this email directly, [view it on GitHub](https://github.com/luizpicol
o/rails_admin_dropzone/issues/1#issuecomment-224094959), or [mute the thread](
https://github.com/notifications/unsubscribe/ABT0W4EWVf_Ls2mNhSbnwR8aTewdePU7k
s5qJJHWgaJpZM4Iujbi).![](https://github.com/notifications/beacon/ABT0W5zPuMkrf
io54oZGyeJHHiBsCI0Vks5qJJHWgaJpZM4Iujbi.gif)

**Comment by luizpicolo** [comment]
Not at all :+1:
